### ISSUE TITLE
Entries of missing images

### ISSUE THREAD

**Issue by samedii** [JD-P/simulacra-aesthetic-captions#3]
I'm finding 28780 entries in the database that there are no images for. I thought I had failed in extraction or a corrupted download but I've been unable to find any error as of yet.

Are these images missing intentionally?

Your code in https://github.com/crowsonkb/simulacra-aesthetic-models which builds upon this expects all images to be present or it crashes.

**Comment by kjerk** [comment]
Agreed w/ this, mentioned in another issue https://github.com/JD-P/simulacra-aesthetic-captions/issues/1#issuecomment-1190211706 
but it seems like this goes both directions, there are a bunch of images that do not have ratings as well.

**Comment by JD-P** [comment]
Sorry about that, I need to update the URL used to grab the dataset. This URL works: [https://s3.us-west-1.wasabisys.com/simulacrabot/sac.tar](https://s3.us-west-1.wasabisys.com/simulacrabot/sac.tar)

**Comment by samedii** [comment]
Thank you! 🙂

**Comment by kjerk** [comment]
Yes, thanks for the update!
